# version format
version: 1.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

## branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Build worker image (VM template)
image: Ubuntu
# clone directory
clone_folder: /dynamodb-provisioner

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

install:
  - sh: chmod +x /dynamodb-provisioner/install-dynamodb.sh
  - sh: /dynamodb-provisioner/install-dynamodb.sh
build_script:
  - dotnet build

build:
  publish_nuget: true
  
test_script:
  # run the unit tests (requires changing into the test directory)
  - sh: cd Pushpay.DynamoDbProvisioner.Tests
  - sh: dotnet test

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

deploy:
  - provider: NuGet
    api_key:
      secure: Qs7MhmLNfpi2VesIAdBTzRfFfoSSkfNPg4qdlunymy1QLK3oq6N2MBjfk8saEswq
    skip_symbols: true